[package]
name = "day19"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7"
once_cell = "1.16.0"
rand = "0.8.5"
